# Generated by Django 5.1.4 on 2025-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_model',
            old_name='brand',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='books_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/media/uploads/'),
        ),
    ]
