# Generated by Django 5.1.4 on 2025-01-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_brand_books_model_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowmodel',
            name='quantity',
        ),
    ]
