# Generated by Django 5.1.4 on 2025-01-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_borrowmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowmodel',
            name='isReturn',
            field=models.BooleanField(default=False),
        ),
    ]
