# Generated by Django 5.1.4 on 2025-01-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_transactionsmodel'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Borrow'), (3, 'Return')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booksr', to='book.books_model')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_transactions', to='profiles.useraccount')),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionsModel',
        ),
    ]
